import { ItineraryDay, ActivityType } from './types';

// Your images should be placed in a `public/images` folder.
// For example, the image for Mount Abu should be at `public/images/mount-abu.jpg`.

export const ITINERARY_DATA: ItineraryDay[] = [
  {
    day: 0,
    date: 'Friday, January 23rd, 2026',
    title: 'The Journey Begins',
    city: 'Pune',
    color: 'white',
    coords: { lat: 18.5204, lng: 73.8567 },
    imageUrl: '',
    activities: [
      { type: ActivityType.TravelTrain, description: 'Board the 16210 Ajmer Express from Pune.', time: '5:50 PM' },
      { type: ActivityType.TravelTrain, description: 'Mixed day/night journey.' },
    ],
  },
  {
    day: 1,
    date: 'Saturday, January 24th',
    title: 'The Green Oasis',
    city: 'Mount Abu',
    color: 'emerald',
    coords: { lat: 24.5926, lng: 72.7156 },
    imageUrl: '/images/mount-abu.jpg',
    activities: [
      { type: ActivityType.Arrival, description: 'Arrive at Abu Road station (ABR).', time: '10:45 AM' },
      { type: ActivityType.Explore, description: 'Transfer to Mount Abu and check into your hotel.' },
      { type: ActivityType.Explore, description: 'Visit the Dilwara Temples and Nakki Lake.' },
      { type: ActivityType.Stay, description: '1 Night in Mount Abu.' },
    ],
  },
  {
    day: 2,
    date: 'Sunday, January 25th',
    title: 'The White City',
    city: 'Udaipur',
    color: 'slate',
    coords: { lat: 24.5854, lng: 73.7125 },
    imageUrl: '/images/udaipur.jpg',
    activities: [
      { type: ActivityType.TravelBus, description: 'Daytime Travel (3-4 hours) by bus to Udaipur.' },
      { type: ActivityType.Arrival, description: 'Arrive in the afternoon and check in.' },
      { type: ActivityType.Experience, description: 'Enjoy a sunset boat ride on Lake Pichola.' },
      { type: ActivityType.Stay, description: '1 Night in Udaipur.' },
    ],
  },
  {
    day: 3,
    date: 'Monday, January 26th',
    title: 'Republic Day in Udaipur',
    city: 'Udaipur',
    color: 'slate',
    coords: { lat: 24.5854, lng: 73.7125 },
    imageUrl: '/images/udaipur.jpg',
    activities: [
      { type: ActivityType.Explore, description: "Explore Udaipur's magnificent City Palace and the old city's charm." },
      { type: ActivityType.TravelTrain, description: 'Board a late-night train from Udaipur to Jaipur.' },
    ],
  },
  {
    day: 4,
    date: 'Tuesday, January 27th',
    title: 'The Pink City',
    city: 'Jaipur',
    color: 'rose',
    coords: { lat: 26.9124, lng: 75.7873 },
    imageUrl: '/images/jaipur.jpg',
    activities: [
      { type: ActivityType.Arrival, description: 'Arrive in Jaipur in the morning.' },
      { type: ActivityType.Explore, description: 'Visit the City Palace, Jantar Mantar, and Hawa Mahal.' },
      { type: ActivityType.Stay, description: '1 Night in Jaipur.' },
    ],
  },
  {
    day: 5,
    date: 'Wednesday, January 28th',
    title: 'Amber Fort Majesty',
    city: 'Jaipur',
    color: 'rose',
    coords: { lat: 26.9124, lng: 75.7873 },
    imageUrl: '/images/jaipur.jpg',
    activities: [
      { type: ActivityType.Explore, description: 'Visit the spectacular Amber Fort.' },
      { type: ActivityType.TravelTrain, description: 'Board a late-night train from Jaipur to Bikaner.' },
    ],
  },
  {
    day: 6,
    date: 'Thursday, January 29th',
    title: 'The Red City',
    city: 'Bikaner',
    color: 'red',
    coords: { lat: 28.0229, lng: 73.3119 },
    imageUrl: '/images/bikaner.jpg',
    activities: [
      { type: ActivityType.Arrival, description: 'Arrive in Bikaner in the morning.' },
      { type: ActivityType.Explore, description: 'Visit the unconquered Junagarh Fort and the unique Karni Mata Temple.' },
      { type: ActivityType.Stay, description: '1 Night in Bikaner.' },
    ],
  },
  {
    day: 7,
    date: 'Friday, January 30th',
    title: 'The Golden City',
    city: 'Jaisalmer',
    color: 'amber',
    coords: { lat: 26.9157, lng: 70.9083 },
    imageUrl: '/images/jaisalmer.jpg',
    activities: [
      { type: ActivityType.TravelBus, description: 'Daytime Travel (6-7 hours) by morning bus to Jaisalmer.' },
      { type: ActivityType.Arrival, description: 'Arrive late afternoon, head to desert camp at Sam Sand Dunes.' },
      { type: ActivityType.Experience, description: 'Enjoy a sunset camel safari and a traditional cultural program.' },
      { type: ActivityType.Stay, description: '1 Night in a Desert Camp.' },
    ],
  },
  {
    day: 8,
    date: 'Saturday, January 31st',
    title: 'Jaisalmer Fort Exploration',
    city: 'Jaisalmer',
    color: 'amber',
    coords: { lat: 26.9157, lng: 70.9083 },
    imageUrl: '/images/jaisalmer.jpg',
    activities: [
      { type: ActivityType.Explore, description: 'After breakfast in the desert, explore the magnificent, living Jaisalmer Fort.' },
      { type: ActivityType.TravelTrain, description: 'Board a late-night train from Jaisalmer to Jodhpur.' },
    ],
  },
  {
    day: 9,
    date: 'Sunday, February 1st',
    title: 'The Blue City',
    city: 'Jodhpur',
    color: 'sky',
    coords: { lat: 26.2389, lng: 73.0243 },
    imageUrl: '/images/jodhpur.jpg',
    activities: [
      { type: ActivityType.Arrival, description: 'Arrive in Jodhpur in the morning.' },
      { type: ActivityType.Explore, description: 'Visit the mighty Mehragarh Fort and explore the Clock Tower market.' },
      { type: ActivityType.Stay, description: '1 Night in Jodhpur.' },
    ],
  },
  {
    day: 10,
    date: 'Monday, February 2nd',
    title: 'Departure from Jodhpur',
    city: 'Jodhpur',
    color: 'sky',
    coords: { lat: 26.2389, lng: 73.0243 },
    imageUrl: '/images/jodhpur.jpg',
    activities: [
      { type: ActivityType.Explore, description: 'Enjoy a final relaxed morning in the Blue City.' },
      { type: ActivityType.Departure, description: 'Head to Jodhpur airport or railway station for your journey home.' },
      { type: ActivityType.TravelPlane, description: 'By Flight: Arrive in Pune the same night.' },
      { type: ActivityType.TravelTrain, description: 'By Train: Board the 11089 BGKT PUNE EXP.', time: '8:20 PM' },
    ],
  },
  {
    day: 11,
    date: 'Tuesday, February 3rd',
    title: 'Arrival in Pune',
    city: 'Pune',
    color: 'white',
    coords: { lat: 18.5204, lng: 73.8567 },
    imageUrl: '',
    activities: [
      { type: ActivityType.Arrival, description: 'If you took the train, you will arrive back in Pune in the afternoon.' },
    ],
  },
];
